### ISSUE TITLE
Self-controlled radar "camera" movement

### ISSUE THREAD

**Issue by getwh1ted** [boltgolt/boltobserv#12]
Suggestion

**Comment by boltgolt** [comment]
Could you elaborate your idea? Would the observer have certain hotkeys that would trigger specific views?

**Comment by getwh1ted** [comment]
Exactly. Hotkeys for: zoom-in, zoom-out, and optional hotkey for following action (place with bomb carrier, most T players etc.)

**Comment by getwh1ted** [comment]
Closed. Auto-zoom option resolves my suggestions
