### ISSUE TITLE
[Question] Is it possible to publish map as a website?

### ISSUE THREAD

**Issue by FlowingSPDG** [boltgolt/boltobserv#18]
Hi man! thanks for develope awesome app :)
Im japanese observer programmer, I'm working on auto GOTV twitch streaming system and Im thinking to add radar page for that twitch channel.
Is it possible to publish radar as a website like [this](https://github.com/FlowingSPDG/GameStateIntegrationWebApp)?
thanks :)

**Comment by boltgolt** [comment]
It is, but not easily. You'll have to rewrite the part of the code that uses ipcRenderer to communicate with the front-end and replace it with a socket.io server.

**Comment by FlowingSPDG** [comment]
Hmm I see... it sounds bit dificult for me :/
I'll try to find other way to do same,but Thanks man! keep it up ;)
