### ISSUE TITLE
Improve dot position accuracy.

### ISSUE THREAD

**Issue by frazer-scully** [boltgolt/boltobserv#19]
Dots will show up slightly off of their actual position.

On nuke, I noticed they showed up higher on the radar than they actually are, sometimes causing players in the ramp area to show in the area between the split maps.

E. After doing some testing & playing about with the offset in meta.json5, I have realised that this is caused by the scaling of the radar. Scaling the radar will cause players to show up in a slightly wrong position.

**Comment by boltgolt** [comment]
I'd like to finally close this if you've confirmed that it now works the way it should
