### ISSUE TITLE
Possible improvements for split maps.

### ISSUE THREAD

**Issue by frazer-scully** [boltgolt/boltobserv#20]
One idea is to hide a section of the map when no players are currently present on it to make the radar look cleaner if being used on stream.

Another is to change the way the vertigo map works, removing overlap to avoid confusion. See LVP hud for an example.

**Comment by boltgolt** [comment]
The latter part is now implemented, first is a lot harder so delaying it

**Comment by boltgolt** [comment]
Closing as won't fix for the first suggestion, too difficult to implement
