### ISSUE TITLE
Loading map on start of the game / weird graphic bug

### ISSUE THREAD

**Issue by mgister** [boltgolt/boltobserv#21]
I found a weird two bugs. 

1) When you start the game the first available map is loading (in my case some 1v1 map). 
2) Lightening on maps is broken. 

This two bugs are related to gamestate_integration config. When I delete config file (or delete the line with "map" "1") bugs disappears.

**Comment by boltgolt** [comment]
Both are quite curious, are you using an unmodded and updated version of CSGO?

**Comment by mgister** [comment]
I found the cause of the error after some research and reinstalling the game. It was my other config file with weird exec command. Eot.
