### ISSUE TITLE
Add csgo overlay feature

### ISSUE THREAD

**Issue by Barsnes** [boltgolt/boltobserv#29]
It would be nice if you can directly overlay the radar onto csgo.

https://github.com/osztenkurden/CS-GO-Observer-Custom-HUD has a feature like this. 

Here is a direct download to the CSGO Hud Overlay https://drive.google.com/file/d/12pAp3BdzFdb-wcW3DqcYJ6P-VMDzLBHu/view

**Comment by boltgolt** [comment]
You can already do that with `window.alwaysOnTop: true` and then playing with `window.defaultSize`, what would be the benefit of an extra executable as custom HUD has?

**Comment by Barsnes** [comment]
What file do I have to change the variable in? can't seem to find it.
It would just be an enhancement to the overall product, not something that is needed, but is there to make life easier.

**Comment by Barsnes** [comment]
> What file do I have to change the variable in? can't seem to find it.
> It would just be an enhancement to the overall product, not something that is needed, but is there to make life easier.

I found the file, sorry I am blind sometimes!

**Comment by boltgolt** [comment]
No problem, might need to add something about the config location in the readme at some point
