### ISSUE TITLE
Perfomance Problems

### ISSUE THREAD

**Issue by NPLznk** [boltgolt/boltobserv#30]
Hey! I love what u did with this map, is gorgeous, me and my team have been trying to use it with a custom hud for a tournament which was streamed and everything. But, we noticed that the map takes a lot of CPU and it has been difficult to stream sometimes, can you give me any tip to make everything go smoother? the game itself goes normal, but in OBS it looks terrible. Same with the hud, the only thing that works well is the map.

**Comment by boltgolt** [comment]
Unfortunately rendering a map at 60 FPS is quite demanding, especially because Boltobserv is basically a browser. Both the HUD and the radar can be rendered on another computer over the network though, you only have to point the GSI file to the right network location

**Comment by NPLznk** [comment]
Yeah, I thought about that, the thing is that our actual host just has only one computer and we've been trying to do everything in that, which is taking a lot of effort out of it. that's why I asked but I supose that if we put better components on the pc it would have better perfomance.
