### ISSUE TITLE
Player z-position

### ISSUE THREAD

**Issue by nutellazpw** [boltgolt/boltobserv#34]
It's unclear if the player is on upper or lower level of the map like this, there needs to be some kind of line or something like on default radar so observer can know if player in question is elevated or not. Example: (de_nuke) You've no way of telling if player is holding ramp angle or he's on the roof.

**Comment by boltgolt** [comment]
Would a split map be a better solution to this?

**Comment by nutellazpw** [comment]
For some positions yes,but for example if the players is under A-Palace (de_mirage) i don't know to player is UNDER palace or ON palace,and more similar situations on everymap.

Radar is great, but i think to this can be good improvement.

**Comment by boltgolt** [comment]
Implemented in 1.0.1
