### ISSUE TITLE
Issue accuracy and Simple Radar Update

### ISSUE THREAD

**Issue by 007sebi007** [boltgolt/boltobserv#35]
<img width="231" alt="Radar Inferno off" src="https://user-images.githubusercontent.com/62571444/83660382-0f2d7880-a5c5-11ea-8828-a3c2cba0337b.png">

Hey Guys!

Do you have any idea, why these guys are "off-road"? Smokes, moly, ... are perfectly placed.

I deleted and downloaded everything again and it keeps the same...
I saw in the maps-files, that there is a meta.json5 and i can change some values... but when i am doing this, all smokes, moly, ... is changing aswell...

Also i want to add, that Simple Radar has released a new version of mirage and added vertigo!
Maybe you will implement this one!

Regrads Sebastian
See ya ^^

**Comment by boltgolt** [comment]
Yeah, this is a know issue unfortunately. It's not really fixable at the moment because smokes are somehow aligned right, while players are not or vise versa

**Comment by 007sebi007** [comment]
> Yeah, this is a know issue unfortunately. It's not really fixable at the moment because smokes are somehow aligned right, while players are not or vise versa

But I think ESL (etc.) are using your script aswell... why it's accurate on their radars?

**Comment by boltgolt** [comment]
ESL uses their own radar, just like blast does. I have a suspicion that others are using Boltobserv with fixed positioning without sharing these fixes. This breaks the license but i can't really do much about it

**Comment by frazer-scully** [comment]
The thing is with the fixes is that nobody knows what is causing the issue. Plus it’s different depending on the scaling of the radar.

I’d be happy to make some configs for a couple of fairly “standard” sizes and share them if people wanted though.
