### ISSUE TITLE
How to edit players' dot colors & XRAY colors changed?

### ISSUE THREAD

**Issue by WertyCaster** [boltgolt/boltobserv#36]
Hi!

First of all, from a freelance caster's point of view, I'd like to thank you for this piece of art! I appreciate the effort 1000x times!

I use a custom HUD since a while ago and I used different colors for CT and Ts, and I would like to edit the dot colors of them on the minimap accordingly. Can you please tell me which file should I edit in order to do that?

Also, since I started using the radar, my XRAY colors changed all to red. Do you have any idea why? Anyway, would you know how to edit them?

**Comment by boltgolt** [comment]
Thanks for the kind words!

You can add CSS rules in [custom.css ](https://github.com/boltgolt/boltobserv/blob/master/css/custom.css)if you want to apply custom styling. In your case you can change the background color of the T and CT dots.

Howdy doesn't do anything with the game itself, there's no way it changes xray colors

**Comment by WertyCaster** [comment]
Solved the issue with XRAY, not your fault, sorry!
Can you by any chance help with those lines? Unfortunately I'm a Law School graduate and have no idea in programming :(

Those are the colors:
CT: #0057fa || OR || rgba(0, 87, 250, 1)
Terrorist: #fa5700 || OR || rgba(250, 87, 0, 1)
Having this Terrorist color, the bomb carrier would have the same color like them, so the bomb carrier should also have his color changed to red.
Bomb carrier: #fa0000 || OR || rgba(250, 0, 0, 1)

I would really appreciate the help. Thanks a lot, boltgolt!

**Comment by boltgolt** [comment]
You can insert `background: #0057fa;` between the `{ }` of the selectors you want to recolor, make sure you use the right color codes

**Comment by WertyCaster** [comment]
Done! Thank you very much!
Just two side questions, and excuse me for asking you, but I really don't seem to find any fix anywhere.
As I changed those colors on the whole HUD and now the radar with your help, two problem remain:
1. Killfeed colors are still the default ones.
2. XRAY colors are still the default ones.
Does it happen you to know how should I change those?
I really appreciate the whole help, thank you a lot!

**Comment by boltgolt** [comment]
I'm not the developer of the HUD you're using so i can't really comment on that 

The file your looking for is `config.json5` in the config folder
