### ISSUE TITLE
it just show the map but the player location no 

### ISSUE THREAD

**Issue by Zvondaaa** [boltgolt/boltobserv#55]

**Comment by boltgolt** [comment]
Please use more words to describe the issue. What setup, kind of match, map, version, etc

**Comment by Zvondaaa** [comment]
Version 1.0.1 , map inferno , https://ibb.co/f2ps9qK

**Comment by boltgolt** [comment]
Are you a player in this game or an observer?

**Comment by hackerjpj** [comment]
I have the same problem
No people are displayed, only the map background

**Comment by hackerjpj** [comment]
@Zvondaaa   I have the same problem as you

**Comment by boltgolt** [comment]
@Zvondaaa was in a live deathmatch game so probably poor mans attempt a cheating, closing
