### ISSUE TITLE
Tried all versions, just a background map

### ISSUE THREAD

**Issue by hackerjpj** [boltgolt/boltobserv#56]
Only the map is displayed, nothing else is displayed. He needs to be updated

**Comment by boltgolt** [comment]
Show me a screenshot of csgo with the radar running

**Comment by hackerjpj** [comment]
![111](https://user-images.githubusercontent.com/57884812/145789884-5a842771-ae7c-4069-b871-a53d0c1d8aec.jpg)
![2222](https://user-images.githubusercontent.com/57884812/145789892-b797e7ab-22a2-4c85-8d7a-7aa86560142c.jpg)

**Comment by hackerjpj** [comment]
@boltgolt  Does game data reading belong to internal injection?

**Comment by boltgolt** [comment]
You are not an observer in that game, where did you find boltobserv?

**Comment by boltgolt** [comment]
Seems to be a really poor attempt at cheating, closing
