### ISSUE TITLE
Enhancement request: Floating names in addtion to numbers on player dots

### ISSUE THREAD

**Issue by paulsnoops** [boltgolt/boltobserv#61]
Please would it be possible to add floating names to the player dots so that I can see who is who? Maybe make it so you can edit how they look in the config?

Also, while I'm here. If I was to add my own map for the ones not supported where can I get the info needed for the meta.json5 file?

Thank you

**Comment by boltgolt** [comment]
Do you mean swapping the player slot numbers for their names? Sounds like it could get really messy with a lot of players in one place but worth implementing if others would like it too 

The meta.json is mostly trial and error to see what works. The resolution is possible to be calculated by taking 2 points on the radar, and then measuring how many pixels are between them on the image and how many units are between them in game. Most other values are just adjusting till it is correct

**Comment by paulsnoops** [comment]
I'd imagine either replacing the numbers or have the name floating underneath. What about if it's optional and defaults to false? Would also be cool if you could enable/disable by hotkey?

**Comment by ReneRebsdorf** [comment]
+1 for an option for this. Maybe include a truncation limit as a variable as well?
I would definitely use this option in place of the numbers. Leetify and scope.gg do this for their 2d views in browser and it works quite well.
