### ISSUE TITLE
Ancient Map Outdated

### ISSUE THREAD

**Issue by DanielZint** [boltgolt/boltobserv#62]
The latest changes on Ancient were not (yet) added. An update would be highly appreciated. If someone could point out, where I can find maps online that would be also great. I could not find any.

**Comment by boltgolt** [comment]
The radar backgrounds in Boltobserv come from Simple Radar and unfortunately the person who has put a lot of sweat and tears into SR over the years is currently very very busy. I'll put out an update as soon as the new radar is available

**Comment by DanielZint** [comment]
A friend of mine adapted the Ancient map. It is not pixel perfect but it does its job. So for me, this issue could be closed now but I leave it up to you.

![Ancient Radar Cast_00000](https://user-images.githubusercontent.com/44882049/184840400-9e737350-04f6-474b-8024-1fba6d36486b.png)

**Comment by boltgolt** [comment]
This one was fixed in 1.2.0, closing now
