### ISSUE TITLE
Why I only have a blank map here

### ISSUE THREAD

**Issue by 1822745224** [boltgolt/boltobserv#72]
Why I only have a blank map here

**Comment by 1822745224** [comment]
![图片](https://user-images.githubusercontent.com/53213053/213746660-605a43e6-60fa-42f8-9733-a03819eab2ed.png)
![图片](https://user-images.githubusercontent.com/53213053/213746722-66bd7992-0310-45e6-8e18-f255110da932.png)

**Comment by boltgolt** [comment]
This it not a cheating tool.
