### ISSUE TITLE
not showing on map

### ISSUE THREAD

**Issue by sniedzins12** [boltgolt/boltobserv#75]
I need help, I just clicked install cfg and it installed, it  shows launch the game i did and after opening external map, while im in the server, external radar not showing enything, any help?

**Comment by boltgolt** [comment]
Cheating is real lame, don't be like that

**Comment by sniedzins12** [comment]
lol, why u created then?

**Comment by boltgolt** [comment]
Have you read the tag line? The "made specifically for observing" part? 

Imagine being so incredibly insecure that not only do you need to cheat at a video game, you also get upset when someone calls you out on it.
