### ISSUE TITLE
i cant see people on the map  when i am on community server or practice with bots is it just ingame

### ISSUE THREAD

**Issue by flicsyss** [boltgolt/boltobserv#77]
![Counter-strike  Global Offensive Screenshot 2023 04 10 - 20 43 45 32](https://user-images.githubusercontent.com/130398635/230970872-04e93ff3-1323-4979-b649-73dee08b912a.png)
![image](https://user-images.githubusercontent.com/130398635/230970966-9ddf09ca-1937-436a-9520-061fbb845266.png)

**Comment by boltgolt** [comment]
This is an observing tool, try observing a match
