### ISSUE TITLE
Error reading *map file

### ISSUE THREAD

**Issue by MattPlayGamez** [boltgolt/boltobserv#82]
![image](https://github.com/boltgolt/boltobserv/assets/62027538/b401951f-e8bd-4a60-b938-87b4dcf862a4)
This is issue with all current maps, look at the screenshot above

**Comment by boltgolt** [comment]
Have you tried it on dust2? Boltobserv does not support canals

**Comment by MattPlayGamez** [comment]
Do you Mean de_dust2_old?

Op zo 16 jul. 2023 12:10 schreef boltgolt ***@***.***>:

**Comment by boltgolt** [comment]
Nee ik bedoel `map de_dust2`, of is dit in CS2?

**Comment by MattPlayGamez** [comment]
Ah ok, Het is de originele CS:GO.
Lukt dit enkel voor 1 map of meerdere?
Indien 1, Is het moeilijk om meerdere mappen te maken of integreren. Anders zal ik wel proberen meerdere erbij te doen

**Comment by boltgolt** [comment]
Werkt met alle active duty maps en een aantal oudere maps, je kan de hele lijst zien op https://github.com/boltgolt/boltobserv/tree/master/src/maps 

Als je hier een map aan toe wil voegen dan graag natuurlijk! Het vinden van de coördinaten in meta.json5 is alleen niet super makkelijk, das echt trial and error

**Comment by MattPlayGamez** [comment]
Hoe kan ik mappen toevoegen?

**Comment by boltgolt** [comment]
Kijk naar de al bestaande maps hoe die in Boltobserv zitten en boots dat na. In het kort: 

1. Mapje aanmaken met juiste in-game naam 
2. Radar achtergrond image uit de game (of ergens anders) halen en als radar.png opslaan in juiste grote 
3. Definiëren waar een plaats in de in-game wereld overeenkomt met een plaats in de radar. Dit is voornamelijk een beetje gokken. Je moet de `resolution` van de map weten (als je 10 in-game units beweegt, hoeveel px is dat op de radar?) en je moet weten waar de map zich bevind ten opzichte van coördinaat 0,0 en daar de juiste `offset` uit halen. Begin met de meta.json5 van een andere map en verander eerst The offset tot het een beetje in de buurt komt, en dan is het klooien met de resolutie tot het werkt.

**Comment by MattPlayGamez** [comment]
Ok, Ik zal het proberen

**Comment by MattPlayGamez** [comment]
Hoe maak/krijg je die afbeeldingen want deze zijn allemaal hetzelfde, maar niet zoals op de CS:GO minimap

**Comment by boltgolt** [comment]
Die zijn van simple radar, maar als zij het niet hebben kan je er gewoon een uit de gamefiles halen
