### ISSUE TITLE
GSI not connected with CS 2

### ISSUE THREAD

**Issue by denrio157** [boltgolt/boltobserv#93]
Hello, i like and i try your program. HUD is good and normal, but with the radar map, I have some a little problem. I've followed all the notes and directions but still can't connect. Any suggestions?
![image](https://github.com/boltgolt/boltobserv/assets/31591836/a2aa0c91-3711-4533-8ef3-71dbfaa9ca42)
![image](https://github.com/boltgolt/boltobserv/assets/31591836/1df5cdeb-1b71-4552-92f1-4caa1503af44)

**Comment by boltgolt** [comment]
Have you checked if your [gamestate_integration_boltobserv.cfg](https://github.com/boltgolt/boltobserv/blob/master/src/gamestate_integration_boltobserv.cfg) is installed in the correct game folder?

**Comment by denrio157** [comment]
> Have you checked if your [gamestate_integration_boltobserv.cfg](https://github.com/boltgolt/boltobserv/blob/master/src/gamestate_integration_boltobserv.cfg) is installed in the correct game folder?

Of course, I followed all the steps given but it's still the same as that. Are there any steps missed?

**Comment by fyflo** [comment]
The top starter problem has been solved.
Replacing the cfg file
