### ISSUE TITLE
Faceit Couch + dot

### ISSUE THREAD

**Issue by fyflo** [boltgolt/boltobserv#95]
An innovation appeared on Faceit.
Trainers now occupy a player's slot during a match.
Therefore, 1 or 2 players will not be reflected on the radar.
I tried to correlate several files, but it turns out that the players’ movements are broken or disappear completely.
This causes the error `Uncaught TypeError: Cannot read property 'className' of undefined, which cannot create a new class for the weapon (if (global.playerAmmos[player.num][weapon])) `in the file `(playerPosition.js:32)`.
1. Made an adjustment in `the _global.js` file: 83 entries from for `(var i = 0; i < 10; i++) {` to for `(var i = 0; i < 12; i++) {`
2. Added dot in the `map.html` file:
```
<div id="dot11" class="dot"><div id="height11"></div></div>
         <div id="label11" class="label11">11</div>
```

If anyone managed to add new dots to the mini map, please share.

**Comment by TechBarat** [comment]
I have the same problem, due to the "more" players in the teams some of the players are not on the radar.
I have also tried to change some stuff but without luck :(

**Comment by TechBarat** [comment]
UPDATE:
I have also modified in the _global.js file (var i = 0; i < 10; i++) to (var i = 0; i < 12; i++), but in the map.html I have added the following lines, and after that the radar worked fine with all of the players:
`				<div id="dot10" class="dot"><div id="height10"></div></div>
				<div id="label10" class="label">10</div>
				<div id="dot11" class="dot"><div id="height11"></div></div>
				<div id="label11" class="label">11</div>
				<div id="dot12" class="dot"><div id="height12"></div></div>
				<div id="label12" class="label">12</div>`

**Comment by fyflo** [comment]
Adjusted the display of players by buttons on the keyboard.

```
<div id="dot1" class="dot"><div id="height1"></div></div>
        <div id="label1" class="label">2</div>
        <div id="dot2" class="dot"><div id="height2"></div></div>
        <div id="label2" class="label">3</div>
        <div id="dot3" class="dot"><div id="height3"></div></div>
        <div id="label3" class="label">4</div>
        <div id="dot4" class="dot"><div id="height4"></div></div>
        <div id="label4" class="label">5</div>
        <div id="dot5" class="dot"><div id="height5"></div></div>
        <div id="label5" class="label">6</div>
        <div id="dot6" class="dot"><div id="height6"></div></div>
        <div id="label6" class="label">7</div>
        <div id="dot7" class="dot"><div id="height7"></div></div>
        <div id="label7" class="label">8</div>
        <div id="dot8" class="dot"><div id="height8"></div></div>
        <div id="label8" class="label">9</div>
        <div id="dot9" class="dot"><div id="height9"></div></div>
        <div id="label9" class="label">10</div>
        <div id="dot0" class="dot"><div id="height0"></div></div>
        <div id="label0" class="label">1</div>
        <div id="dot10" class="dot"><div id="height10"></div></div>
        <div id="label10" class="label">11</div>
        <div id="dot11" class="dot"><div id="height11"></div></div>
        <div id="label11" class="label">12</div>
        <div id="dot12" class="dot"><div id="height12"></div></div>
        <div id="label12" class="label">13</div>
```
