### ISSUE TITLE
inferno

### ISSUE THREAD

**Issue by fyflo** [boltgolt/boltobserv#97]
Hi all!
Starting today, inferno began to display incorrectly.
It is not located at the coordinates where it should be.
Has anyone figured out the problem?

**Comment by fyflo** [comment]
![2024-06-02 20_30_05-Counter-Strike 2](https://github.com/boltgolt/boltobserv/assets/109218111/5340bbf3-4b7e-4dac-99d8-17a8fd08d563)
![2024-06-02 20_36_13-Developer Tools - http___192 168 0 199_2626_huds_YRpKJZ8SCNLepMCl](https://github.com/boltgolt/boltobserv/assets/109218111/66fade7d-f22c-4eab-93f1-85efc2bba375)

For some reason, the calculation of left and botton is no longer correct

**Comment by fyflo** [comment]
I solved the problem.

**Comment by boltgolt** [comment]
Heuristics were used on the name of the inferno because the actual location in the infernos was very very off sometimes. I guess they finally fixed that? Was your fix to use the actual coords?

**Comment by fyflo** [comment]
@boltgolt HI

For some reason gsi.js stopped working for me and I simply replaced it from version 1.4.0 where there is no division by 2
Also made the width 120: flameElement[i].style.height = flameElement[i].style.width =
 (120 / global.mapData.resolution / 1024) * 100 + "%";

Test it just in case.

![2024-06-03 17_05_31-CSGO OVERLAY FOR CUSTOM HUD](https://github.com/boltgolt/boltobserv/assets/109218111/e1f1465c-6cb8-4285-a1d1-1314286700f8)
